# -*- coding: utf-8 -*-
"""Semaforoconferencia.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1grg2ZdXgXMndb6Z_QiNXgp7y1xUDgeD_
"""

import threading

class Conferencia:
    def __init__(self):
        self.microfono = threading.Semaphore(1)

    def usarmicrofono(self, asistente):
        self.microfono.acquire()
        print(f"{asistente} está usando el micrófono.")

        # Simulación de la persona hablando
        print(f"{asistente}: ¡Hola a todos!")
        print(f"{asistente}: Gracias por la conferencia.")
        self.microfono.release()

if __name__ == "__main__":
    sala = Conferencia()

    # Simulación de asistentes utilizando el micrófono
    asistentes = ["Lismary", "Emily", "Kelvin", "Karla"]

    for asistente in asistentes:
        threading.Thread(target=sala.usar_microfono, args=(asistente,)).start()